// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { defaultsDefaultsGet, healthzHealthzGet, type Options, transformWorkbookEndpointTransformWorkbookPost } from '../sdk.gen';
import type { DefaultsDefaultsGetData, DefaultsDefaultsGetResponse, HealthzHealthzGetData, HealthzHealthzGetResponse, TransformWorkbookEndpointTransformWorkbookPostData, TransformWorkbookEndpointTransformWorkbookPostError, TransformWorkbookEndpointTransformWorkbookPostResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const healthzHealthzGetQueryKey = (options?: Options<HealthzHealthzGetData>) => createQueryKey('healthzHealthzGet', options);

/**
 * Healthz
 */
export const healthzHealthzGetOptions = (options?: Options<HealthzHealthzGetData>) => queryOptions<HealthzHealthzGetResponse, DefaultError, HealthzHealthzGetResponse, ReturnType<typeof healthzHealthzGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await healthzHealthzGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: healthzHealthzGetQueryKey(options)
});

export const defaultsDefaultsGetQueryKey = (options?: Options<DefaultsDefaultsGetData>) => createQueryKey('defaultsDefaultsGet', options);

/**
 * Defaults
 */
export const defaultsDefaultsGetOptions = (options?: Options<DefaultsDefaultsGetData>) => queryOptions<DefaultsDefaultsGetResponse, DefaultError, DefaultsDefaultsGetResponse, ReturnType<typeof defaultsDefaultsGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await defaultsDefaultsGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: defaultsDefaultsGetQueryKey(options)
});

/**
 * Transform Workbook Endpoint
 */
export const transformWorkbookEndpointTransformWorkbookPostMutation = (options?: Partial<Options<TransformWorkbookEndpointTransformWorkbookPostData>>): UseMutationOptions<TransformWorkbookEndpointTransformWorkbookPostResponse, TransformWorkbookEndpointTransformWorkbookPostError, Options<TransformWorkbookEndpointTransformWorkbookPostData>> => {
    const mutationOptions: UseMutationOptions<TransformWorkbookEndpointTransformWorkbookPostResponse, TransformWorkbookEndpointTransformWorkbookPostError, Options<TransformWorkbookEndpointTransformWorkbookPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await transformWorkbookEndpointTransformWorkbookPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
