import type { InputTag } from "@/api/client";

export const defaultInputTag: InputTag = {
  codon_maps: [
    {
      name: "Expression Optimization",
      A: "GCC",
      C: "TGC",
      D: "GAC",
      E: "GAA",
      F: "TTC",
      G: "GGC",
      H: "CAC",
      I: "ATC",
      K: "AAA",
      L: "CTC",
      M: "ATG",
      N: "AAC",
      P: "CCC",
      Q: "CAA",
      R: "AGA",
      S: "AGC",
      T: "ACC",
      V: "GTC",
      W: "TGG",
      Y: "TAC",
    },
    {
      name: "Production Optimization",
      A: "GCT",
      C: "TGT",
      D: "GAT",
      E: "GAG",
      F: "TTT",
      G: "GGT",
      H: "CAT",
      I: "ATT",
      K: "AAG",
      L: "TTG",
      M: "ATG",
      N: "AAT",
      P: "CCT",
      Q: "CAG",
      R: "CGT",
      S: "TCT",
      T: "ACT",
      V: "GTT",
      W: "TGG",
      Y: "TAT",
    },
    {
      name: "NextHighestFrequency",
      A: "GCA",
      C: "TGC",
      D: "GAC",
      E: "GAG",
      F: "TTC",
      G: "GGA",
      H: "CAC",
      I: "ATA",
      K: "AAG",
      L: "CTG",
      M: "ATG",
      N: "AAC",
      P: "CCA",
      Q: "CAG",
      R: "CGG",
      S: "TCC",
      T: "ACA",
      V: "GTG",
      W: "TGG",
      Y: "TAC",
    },
  ],
  regions: [
    {
      name: "AA452_7merSubs",
      length: 7,
      substitution: true,
      wild_type: "AACGGTTCTGGACAGAATCAA",
      predecessor: null,
      start_tail: "aatccactcatcgaccaatacttgtactatctctcTaGAactatt",
      end_tail: "caaacgctaaaattcagtgtggccg",
      reverse_complement: false,
      constant_nt: false,
      has_custom_upstream_tail_annotation_length: false,
      has_custom_downstream_tail_annotation_length: false,
      custom_upstream_tail_annotation_length: 0,
      custom_downstream_tail_annotation_length: 0,
    },
    {
      name: "AA588_UpstreamFlank",
      length: 2,
      substitution: true,
      wild_type: "GCCCAA",
      predecessor: null,
      start_tail: "ggccacaaaccaccagagt",
      end_tail: "",
      reverse_complement: true,
      constant_nt: false,
      has_custom_upstream_tail_annotation_length: false,
      has_custom_downstream_tail_annotation_length: false,
      custom_upstream_tail_annotation_length: 0,
      custom_downstream_tail_annotation_length: 0,
    },
    {
      name: "AA588_7merInsert",
      length: 7,
      substitution: false,
      wild_type: "",
      predecessor: "AA588_UpstreamFlank",
      start_tail: "",
      end_tail: "gcgcagaccggTtgggttcaaaaccaagg",
      reverse_complement: true,
      constant_nt: false,
      has_custom_upstream_tail_annotation_length: false,
      has_custom_downstream_tail_annotation_length: false,
      custom_upstream_tail_annotation_length: 0,
      custom_downstream_tail_annotation_length: 0,
    },
    {
      name: "AA588_DownstreamFlank",
      length: 2,
      substitution: true,
      wild_type: "GCACAG",
      predecessor: "AA588_7merInsert",
      start_tail: "ggccacaaaccaccagagt",
      end_tail: "gcgcagaccggTtgggttcaaaaccaagg",
      reverse_complement: true,
      constant_nt: false,
      has_custom_upstream_tail_annotation_length: false,
      has_custom_downstream_tail_annotation_length: false,
      custom_upstream_tail_annotation_length: 0,
      custom_downstream_tail_annotation_length: 0,
    },
  ],
  designs: [
    {
      id: "ID1",
      version: 0,
      region_designs: {
        AA452_7merSubs: "Expression Optimization",
        AA588_UpstreamFlank: "Expression Optimization",
        AA588_7merInsert: "Expression Optimization",
        AA588_DownstreamFlank: "Expression Optimization",
      },
    },
  ],
  design_column_name: "",
};
