// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { HealthzHealthzGetData, HealthzHealthzGetResponses, TransformWorkbookEndpointTransformWorkbookPostData, TransformWorkbookEndpointTransformWorkbookPostErrors, TransformWorkbookEndpointTransformWorkbookPostResponses } from './types.gen';
import { zHealthzHealthzGetData, zHealthzHealthzGetResponse, zTransformWorkbookEndpointTransformWorkbookPostData, zTransformWorkbookEndpointTransformWorkbookPostResponse } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Healthz
 */
export const healthzHealthzGet = <ThrowOnError extends boolean = false>(options?: Options<HealthzHealthzGetData, ThrowOnError>) => (options?.client ?? client).get<HealthzHealthzGetResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zHealthzHealthzGetData.parseAsync(data),
    responseValidator: async (data) => await zHealthzHealthzGetResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/healthz',
    ...options
});

/**
 * Transform Workbook Endpoint
 */
export const transformWorkbookEndpointTransformWorkbookPost = <ThrowOnError extends boolean = false>(options: Options<TransformWorkbookEndpointTransformWorkbookPostData, ThrowOnError>) => (options.client ?? client).post<TransformWorkbookEndpointTransformWorkbookPostResponses, TransformWorkbookEndpointTransformWorkbookPostErrors, ThrowOnError>({
    requestValidator: async (data) => await zTransformWorkbookEndpointTransformWorkbookPostData.parseAsync(data),
    responseValidator: async (data) => await zTransformWorkbookEndpointTransformWorkbookPostResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/transform-workbook',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
