// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://openapi.json` | (string & {});
};

/**
 * CodonMapSpec
 */
export type CodonMapSpec = {
    /**
     * Name
     */
    name: string;
    /**
     * A
     */
    A: string;
    /**
     * C
     */
    C: string;
    /**
     * D
     */
    D: string;
    /**
     * E
     */
    E: string;
    /**
     * F
     */
    F: string;
    /**
     * G
     */
    G: string;
    /**
     * H
     */
    H: string;
    /**
     * I
     */
    I: string;
    /**
     * K
     */
    K: string;
    /**
     * L
     */
    L: string;
    /**
     * M
     */
    M: string;
    /**
     * N
     */
    N: string;
    /**
     * P
     */
    P: string;
    /**
     * Q
     */
    Q: string;
    /**
     * R
     */
    R: string;
    /**
     * S
     */
    S: string;
    /**
     * T
     */
    T: string;
    /**
     * V
     */
    V: string;
    /**
     * W
     */
    W: string;
    /**
     * Y
     */
    Y: string;
};

/**
 * DesignSpec
 */
export type DesignSpec = {
    /**
     * Id
     */
    id: string;
    /**
     * Version
     */
    version: number;
    /**
     * Region Designs
     */
    region_designs: {
        [key: string]: string;
    };
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * InputTag
 */
export type InputTag = {
    /**
     * Codon Maps
     */
    codon_maps: Array<CodonMapSpec>;
    /**
     * Regions
     */
    regions: Array<RegionSpec>;
    /**
     * Designs
     */
    designs: Array<DesignSpec>;
    /**
     * Design Column Name
     */
    design_column_name?: string;
};

/**
 * RegionSpec
 */
export type RegionSpec = {
    /**
     * Name
     */
    name: string;
    /**
     * Length
     */
    length: number;
    /**
     * Substitution
     */
    substitution: boolean;
    /**
     * Wild Type
     */
    wild_type?: string;
    /**
     * Predecessor
     */
    predecessor?: string | null;
    /**
     * Start Tail
     */
    start_tail?: string;
    /**
     * End Tail
     */
    end_tail?: string;
    /**
     * Reverse Complement
     */
    reverse_complement?: boolean;
    /**
     * Constant Nt
     */
    constant_nt?: boolean;
    /**
     * Has Custom Upstream Tail Annotation Length
     */
    has_custom_upstream_tail_annotation_length?: boolean;
    /**
     * Has Custom Downstream Tail Annotation Length
     */
    has_custom_downstream_tail_annotation_length?: boolean;
    /**
     * Custom Upstream Tail Annotation Length
     */
    custom_upstream_tail_annotation_length?: number;
    /**
     * Custom Downstream Tail Annotation Length
     */
    custom_downstream_tail_annotation_length?: number;
};

/**
 * TransformWorkbookRequest
 */
export type TransformWorkbookRequest = {
    /**
     * Input File Name
     */
    input_file_name: string;
    /**
     * Input File Media Type
     */
    input_file_media_type: string;
    /**
     * Input File Base64
     */
    input_file_base64: string;
    input_tag: InputTag;
    /**
     * Input Share Url
     */
    input_share_url?: string | null;
};

/**
 * TransformWorkbookResponse
 */
export type TransformWorkbookResponse = {
    /**
     * Output File Name
     */
    output_file_name: string;
    /**
     * Output File Media Type
     */
    output_file_media_type: string;
    /**
     * Output File Base64
     */
    output_file_base64: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type HealthzHealthzGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type HealthzHealthzGetResponses = {
    /**
     * Response Healthz Healthz Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthzHealthzGetResponse = HealthzHealthzGetResponses[keyof HealthzHealthzGetResponses];

export type TransformWorkbookEndpointTransformWorkbookPostData = {
    body: TransformWorkbookRequest;
    path?: never;
    query?: never;
    url: '/transform-workbook';
};

export type TransformWorkbookEndpointTransformWorkbookPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TransformWorkbookEndpointTransformWorkbookPostError = TransformWorkbookEndpointTransformWorkbookPostErrors[keyof TransformWorkbookEndpointTransformWorkbookPostErrors];

export type TransformWorkbookEndpointTransformWorkbookPostResponses = {
    /**
     * Successful Response
     */
    200: TransformWorkbookResponse;
};

export type TransformWorkbookEndpointTransformWorkbookPostResponse = TransformWorkbookEndpointTransformWorkbookPostResponses[keyof TransformWorkbookEndpointTransformWorkbookPostResponses];
