// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * CodonMapSpec
 */
export const zCodonMapSpec = z.object({
    name: z.string().min(1).max(100),
    A: z.string(),
    C: z.string(),
    D: z.string(),
    E: z.string(),
    F: z.string(),
    G: z.string(),
    H: z.string(),
    I: z.string(),
    K: z.string(),
    L: z.string(),
    M: z.string(),
    N: z.string(),
    P: z.string(),
    Q: z.string(),
    R: z.string(),
    S: z.string(),
    T: z.string(),
    V: z.string(),
    W: z.string(),
    Y: z.string()
});

/**
 * DesignSpec
 */
export const zDesignSpec = z.object({
    id: z.string().min(1).max(100),
    version: z.int().gte(0),
    region_designs: z.record(z.string(), z.string())
});

/**
 * RegionSpec
 */
export const zRegionSpec = z.object({
    name: z.string().min(1).max(100),
    length: z.int().gte(0),
    substitution: z.boolean(),
    wild_type: z.optional(z.string()).default(''),
    predecessor: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    start_tail: z.optional(z.string()).default(''),
    end_tail: z.optional(z.string()).default(''),
    reverse_complement: z.optional(z.boolean()).default(false),
    constant_nt: z.optional(z.boolean()).default(false),
    has_custom_upstream_tail_annotation_length: z.optional(z.boolean()).default(false),
    has_custom_downstream_tail_annotation_length: z.optional(z.boolean()).default(false),
    custom_upstream_tail_annotation_length: z.optional(z.int().gte(0)).default(0),
    custom_downstream_tail_annotation_length: z.optional(z.int().gte(0)).default(0)
});

/**
 * InputTag
 */
export const zInputTag = z.object({
    codon_maps: z.array(zCodonMapSpec),
    regions: z.array(zRegionSpec),
    designs: z.array(zDesignSpec),
    design_column_name: z.optional(z.string()).default('')
});

/**
 * TransformWorkbookRequest
 */
export const zTransformWorkbookRequest = z.object({
    input_file_name: z.string().min(1),
    input_file_media_type: z.string().min(1),
    input_file_base64: z.string().min(1),
    input_tag: zInputTag,
    input_share_url: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * TransformWorkbookResponse
 */
export const zTransformWorkbookResponse = z.object({
    output_file_name: z.string(),
    output_file_media_type: z.string(),
    output_file_base64: z.string()
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    loc: z.array(z.union([z.string(), z.int()])),
    msg: z.string(),
    type: z.string(),
    input: z.optional(z.unknown()),
    ctx: z.optional(z.record(z.string(), z.unknown()))
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.optional(z.array(zValidationError))
});

export const zHealthzHealthzGetData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Response Healthz Healthz Get
 *
 * Successful Response
 */
export const zHealthzHealthzGetResponse = z.record(z.string(), z.string());

export const zDefaultsDefaultsGetData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zDefaultsDefaultsGetResponse = zInputTag;

export const zTransformWorkbookEndpointTransformWorkbookPostData = z.object({
    body: zTransformWorkbookRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zTransformWorkbookEndpointTransformWorkbookPostResponse = zTransformWorkbookResponse;
