from __future__ import annotations

from typing import Final

AMINO_ACID_TO_CODONS: Final[dict[str, tuple[str, ...]]] = {
    "A": ("GCT", "GCC", "GCA", "GCG"),
    "C": ("TGT", "TGC"),
    "D": ("GAT", "GAC"),
    "E": ("GAA", "GAG"),
    "F": ("TTT", "TTC"),
    "G": ("GGT", "GGC", "GGA", "GGG"),
    "H": ("CAT", "CAC"),
    "I": ("ATT", "ATC", "ATA"),
    "K": ("AAA", "AAG"),
    "L": ("CTT", "CTC", "CTA", "CTG", "TTA", "TTG"),
    "M": ("ATG",),
    "N": ("AAT", "AAC"),
    "P": ("CCT", "CCC", "CCA", "CCG"),
    "Q": ("CAA", "CAG"),
    "R": ("CGT", "CGC", "CGA", "CGG", "AGA", "AGG"),
    "S": ("TCT", "TCC", "TCA", "TCG", "AGT", "AGC"),
    "T": ("ACT", "ACC", "ACA", "ACG"),
    "V": ("GTT", "GTC", "GTA", "GTG"),
    "W": ("TGG",),
    "Y": ("TAT", "TAC"),
}

CODON_TO_AMINO_ACID: Final[dict[str, str]] = {
    codon: amino_acid
    for amino_acid, codons in AMINO_ACID_TO_CODONS.items()
    for codon in codons
}

NUCLEOTIDE_COMPLEMENTS: Final[dict[str, str]] = {
    "A": "T",
    "C": "G",
    "G": "C",
    "T": "A",
    "a": "t",
    "c": "g",
    "g": "c",
    "t": "a",
}

DEFAULT_CODON_MAPS: Final[tuple[dict[str, str], ...]] = (
    {
        "name": "Expression Optimization",
        "A": "GCC",
        "C": "TGC",
        "D": "GAC",
        "E": "GAA",
        "F": "TTC",
        "G": "GGC",
        "H": "CAC",
        "I": "ATC",
        "K": "AAA",
        "L": "CTC",
        "M": "ATG",
        "N": "AAC",
        "P": "CCC",
        "Q": "CAA",
        "R": "AGA",
        "S": "AGC",
        "T": "ACC",
        "V": "GTC",
        "W": "TGG",
        "Y": "TAC",
    },
    {
        "name": "Production Optimization",
        "A": "GCT",
        "C": "TGT",
        "D": "GAT",
        "E": "GAG",
        "F": "TTT",
        "G": "GGT",
        "H": "CAT",
        "I": "ATT",
        "K": "AAG",
        "L": "TTG",
        "M": "ATG",
        "N": "AAT",
        "P": "CCT",
        "Q": "CAG",
        "R": "CGT",
        "S": "TCT",
        "T": "ACT",
        "V": "GTT",
        "W": "TGG",
        "Y": "TAT",
    },
    {
        "name": "NextHighestFrequency",
        "A": "GCA",
        "C": "TGC",
        "D": "GAC",
        "E": "GAG",
        "F": "TTC",
        "G": "GGA",
        "H": "CAC",
        "I": "ATA",
        "K": "AAG",
        "L": "CTG",
        "M": "ATG",
        "N": "AAC",
        "P": "CCA",
        "Q": "CAG",
        "R": "CGG",
        "S": "TCC",
        "T": "ACA",
        "V": "GTG",
        "W": "TGG",
        "Y": "TAC",
    },
)

DEFAULT_REGIONS: Final[tuple[dict[str, object], ...]] = (
    {
        "name": "AA452_7merSubs",
        "length": 7,
        "substitution": True,
        "wild_type": "AACGGTTCTGGACAGAATCAA",
        "predecessor": None,
        "start_tail": "aatccactcatcgaccaatacttgtactatctctcTaGAactatt",
        "end_tail": "caaacgctaaaattcagtgtggccg",
        "reverse_complement": False,
        "constant_nt": False,
        "has_custom_upstream_tail_annotation_length": False,
        "has_custom_downstream_tail_annotation_length": False,
        "custom_upstream_tail_annotation_length": 0,
        "custom_downstream_tail_annotation_length": 0,
    },
    {
        "name": "AA588_UpstreamFlank",
        "length": 2,
        "substitution": True,
        "wild_type": "GCCCAA",
        "predecessor": None,
        "start_tail": "ggccacaaaccaccagagt",
        "end_tail": "",
        "reverse_complement": True,
        "constant_nt": False,
        "has_custom_upstream_tail_annotation_length": False,
        "has_custom_downstream_tail_annotation_length": False,
        "custom_upstream_tail_annotation_length": 0,
        "custom_downstream_tail_annotation_length": 0,
    },
    {
        "name": "AA588_7merInsert",
        "length": 7,
        "substitution": False,
        "wild_type": "",
        "predecessor": "AA588_UpstreamFlank",
        "start_tail": "",
        "end_tail": "gcgcagaccggTtgggttcaaaaccaagg",
        "reverse_complement": True,
        "constant_nt": False,
        "has_custom_upstream_tail_annotation_length": False,
        "has_custom_downstream_tail_annotation_length": False,
        "custom_upstream_tail_annotation_length": 0,
        "custom_downstream_tail_annotation_length": 0,
    },
    {
        "name": "AA588_DownstreamFlank",
        "length": 2,
        "substitution": True,
        "wild_type": "GCACAG",
        "predecessor": "AA588_7merInsert",
        "start_tail": "ggccacaaaccaccagagt",
        "end_tail": "gcgcagaccggTtgggttcaaaaccaagg",
        "reverse_complement": True,
        "constant_nt": False,
        "has_custom_upstream_tail_annotation_length": False,
        "has_custom_downstream_tail_annotation_length": False,
        "custom_upstream_tail_annotation_length": 0,
        "custom_downstream_tail_annotation_length": 0,
    },
)
